apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.ovn.org/pod-networks: '{"default":{"ip_addresses":["10.129.0.17/23"],"mac_address":"0a:58:0a:81:00:11","gateway_ips":["10.129.0.1"],"routes":[{"dest":"10.128.0.0/14","nextHop":"10.129.0.1"},{"dest":"172.30.0.0/16","nextHop":"10.129.0.1"},{"dest":"169.254.0.5/32","nextHop":"10.129.0.1"},{"dest":"100.64.0.0/16","nextHop":"10.129.0.1"}],"ip_address":"10.129.0.17/23","gateway_ip":"10.129.0.1","role":"primary"}}'
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "ovn-kubernetes",
          "interface": "eth0",
          "ips": [
              "10.129.0.17"
          ],
          "mac": "0a:58:0a:81:00:11",
          "default": true,
          "dns": {}
      }]
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
    security.openshift.io/validated-scc-subject-type: user
  creationTimestamp: "2025-12-12T11:21:40Z"
  generateName: register-server-676cd8ccd4-
  generation: 1
  labels:
    app: register-server
    pod-template-hash: 676cd8ccd4
  name: register-server-676cd8ccd4-hs2js
  namespace: demo-cocl
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: register-server-676cd8ccd4
    uid: 47df9781-6cfc-4fda-a6e7-0c32c81debba
  resourceVersion: "6125424"
  uid: fc7e2ba2-d182-4256-86b9-c40e92154cb9
spec:
  containers:
  - args:
    - --port
    - "8000"
    image: image-registry.openshift-image-registry.svc:5000/demo-cocl/registration-server:latest
    imagePullPolicy: Always
    name: register-server
    ports:
    - containerPort: 8000
      name: http
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000770000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-n8t74
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: register-server-dockercfg-dg5f8
  nodeName: bb-421-shared-capz-hlhv6-worker-eastus1-rbdt4
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 1000770000
    seLinuxOptions:
      level: s0:c28,c7
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: register-server
  serviceAccountName: register-server
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-n8t74
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
      - configMap:
          items:
          - key: service-ca.crt
            path: service-ca.crt
          name: openshift-service-ca.crt
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-12-18T08:18:33Z"
    observedGeneration: 1
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2025-12-18T08:17:42Z"
    observedGeneration: 1
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-12-18T08:18:53Z"
    observedGeneration: 1
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-12-18T08:18:53Z"
    observedGeneration: 1
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-12-18T08:17:41Z"
    observedGeneration: 1
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: cri-o://763e304d3cef58a53eb06f2dd245c1988cd65fc1252ef6d4618a9f5baef262e1
    image: image-registry.openshift-image-registry.svc:5000/demo-cocl/registration-server:latest
    imageID: image-registry.openshift-image-registry.svc:5000/demo-cocl/registration-server@sha256:f4fddadeb9ff8ff1a99a412cd91f997e60e7f245e584fab3cad06922811cd0fe
    lastState: {}
    name: register-server
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-12-18T08:18:52Z"
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        - 1000770000
        uid: 1000770000
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-n8t74
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.0.128.4
  hostIPs:
  - ip: 10.0.128.4
  observedGeneration: 1
  phase: Running
  podIP: 10.129.0.17
  podIPs:
  - ip: 10.129.0.17
  qosClass: BestEffort
  startTime: "2025-12-18T08:17:42Z"
