apiVersion: v1
kind: Pod
metadata:
  name: trusted-cluster-operator
  namespace: trusted-execution-clusters
  labels:
    component: trusted-cluster-operator
    tier: control-plane
spec:
  hostNetwork: true
  containers:
  - name: trusted-cluster-operator
    command:
    - /usr/bin/operator
    image: quay.io/rhn_support_fjin/trusted-cluster-operator:latest
    imagePullPolicy: IfNotPresent
    env:
    - name: KUBECONFIG
      value: /etc/kubernetes/admin.conf
    - name: BOOTSTRAP_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    resources: {}
    securityContext:
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/admin.conf
      name: kubeconfig
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/admin.conf
      type: FileOrCreate
    name: kubeconfig
